name: Monthly Line Count (cloc)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs at 02:00 UTC on the 1st day of every month.
    - cron: '0 2 1 * *'

jobs:
  generate-cloc-report:
    name: Generate cloc Report
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current commit SHA
        id: get_head_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Restore last cloc-processed SHA from cache
        id: cache-restore-last-sha
        uses: actions/cache/restore@v4
        with:
          path: .last_cloc_processed_sha.txt
          key: cloc-processed-sha-${{ github.ref_name }}

      - name: Decide if cloc needs to run
        id: decide_run
        run: |
          CURRENT_SHA="${{ steps.get_head_sha.outputs.sha }}"
          echo "Current HEAD SHA: $CURRENT_SHA"
          RUN_CLOC="true" # Default to run

          if [[ -f .last_cloc_processed_sha.txt ]]; then
            LAST_PROCESSED_SHA=$(cat .last_cloc_processed_sha.txt)
            echo "Last cloc-processed SHA: $LAST_PROCESSED_SHA"
            if [[ "$CURRENT_SHA" == "$LAST_PROCESSED_SHA" ]]; then
              echo "No new commits on ${{ github.ref_name }} since last cloc run. Skipping."
              RUN_CLOC="false"
            else
              echo "New commits detected. Proceeding with cloc."
            fi
          else
            echo "No previous cloc-processed SHA found in cache (first run or cache expired). Proceeding with cloc."
          fi
          echo "run_cloc=${RUN_CLOC}" >> $GITHUB_OUTPUT

      - name: Install cloc
        if: steps.decide_run.outputs.run_cloc == 'true'
        run: |
          echo "Installing latest cloc from GitHub..."
          # sudo apt-get update # curl doesn't strictly need this, but good if other apt installs were present
          # Ensure curl and perl are installed
          sudo apt-get install -y curl perl
          sudo curl -Lo /usr/local/bin/cloc https://github.com/AlDanial/cloc/releases/latest/download/cloc
          sudo chmod +x /usr/local/bin/cloc
          echo "cloc version:"
          cloc --version

      - name: Run cloc and generate report
        if: steps.decide_run.outputs.run_cloc == 'true'
        id: run_cloc_step
        run: |
          echo "Running cloc..."
          REPORT_FILE="cloc_report_$(date +%Y-%m).txt"
          
          cloc . \
            --exclude-dir=.git,.github,.gradle,build,out,dist,node_modules,vendor \
            --not-match-f='src/DBMS/MS2_Tests_(0[1-9]|10|11)\.java' \
            --not-match-b='^DBAppTests.*' \
            --report-file="$REPORT_FILE"
            
          echo "cloc report generated: $REPORT_FILE"
          echo "--- cloc Report Start ---"
          cat "$REPORT_FILE"
          echo "--- cloc Report End ---"
          
          echo "REPORT_FILENAME=${REPORT_FILE}" >> $GITHUB_ENV
          echo "${{ steps.get_head_sha.outputs.sha }}" > .last_cloc_processed_sha.txt
          echo "Updated .last_cloc_processed_sha.txt with current SHA: ${{ steps.get_head_sha.outputs.sha }}"

      - name: Upload cloc Report Artifact
        if: steps.decide_run.outputs.run_cloc == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cloc-monthly-report-${{ env.REPORT_FILENAME }}
          path: ${{ env.REPORT_FILENAME }}
          retention-days: 90

      - name: Save last cloc-processed SHA to cache
        if: steps.decide_run.outputs.run_cloc == 'true' && steps.run_cloc_step.outcome == 'success'
        uses: actions/cache/save@v4
        with:
          path: .last_cloc_processed_sha.txt
          key: cloc-processed-sha-${{ github.ref_name }}
