name: Monthly Line Count (cloc)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs at 02:00 UTC on the 1st day of every month.
    - cron: '0 2 1 * *'

jobs:
  generate-cloc-report:
    name: Generate cloc Report
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current commit SHA
        id: get_head_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Restore last cloc-processed SHA from cache
        id: cache-restore-last-sha
        uses: actions/cache/restore@v4
        with:
          path: .last_cloc_processed_sha.txt
          key: cloc-processed-sha-${{ github.ref_name }}

      - name: Decide if cloc needs to run
        id: decide_run
        run: |
          CURRENT_SHA="${{ steps.get_head_sha.outputs.sha }}"
          echo "Current HEAD SHA: $CURRENT_SHA"
          echo "Event type: ${{ github.event_name }}"
          RUN_CLOC="true" # Default to run

          if [[ -f .last_cloc_processed_sha.txt ]]; then
            LAST_PROCESSED_SHA=$(cat .last_cloc_processed_sha.txt)
            echo "Last cloc-processed SHA: $LAST_PROCESSED_SHA"
            # Only skip if it's a scheduled run AND the SHAs match
            if [[ "${{ github.event_name }}" == "schedule" && "$CURRENT_SHA" == "$LAST_PROCESSED_SHA" ]]; then
              echo "Scheduled run: No new commits on ${{ github.ref_name }} since last cloc run. Skipping."
              RUN_CLOC="false"
            else
              if [[ "${{ github.event_name }}" == "schedule" ]]; then
                  echo "Scheduled run: New commits detected or SHAs differ. Proceeding with cloc."
              else
                  echo "Non-scheduled run (${{ github.event_name }}): Proceeding with cloc."
              fi
            fi
          else
            echo "No previous cloc-processed SHA found in cache (first run or cache expired). Proceeding with cloc."
          fi
          echo "run_cloc=${RUN_CLOC}" >> $GITHUB_OUTPUT

      - name: Install latest cloc (Perl script)
        if: steps.decide_run.outputs.run_cloc == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y perl
          curl -LfSo cloc https://raw.githubusercontent.com/AlDanial/cloc/master/cloc
          chmod +x cloc
          sudo mv cloc /usr/local/bin/cloc
          cloc --version

      - name: Run cloc and generate report
        if: steps.decide_run.outputs.run_cloc == 'true'
        id: run_cloc_step
        run: |
          echo "Running cloc..."
          REPORT_FILE="cloc_report_$(date +%Y-%m).txt"

          # --not-match-f: Exclude MS2_Tests_01.java, ..., MS2_Tests_11.java
          # --not-match-b: Exclude DBAppTests.java, DBAppTestsMS2.java, etc.
          cloc . \
            --exclude-dir=.git,.github,.gradle,build,out,dist,node_modules,vendor \
            --not-match-f='^MS2_Tests_(0[1-9]|10|11)\.java$' \
            --not-match-b='^DBAppTests.*' \
            --report-file="$REPORT_FILE"

          echo "cloc report generated: $REPORT_FILE"
          echo "--- cloc Report Start ---"
          cat "$REPORT_FILE"
          echo "--- cloc Report End ---"

          echo "REPORT_FILENAME=${REPORT_FILE}" >> $GITHUB_ENV
          # Create/Update the SHA file for caching for the next run
          echo "${{ steps.get_head_sha.outputs.sha }}" > .last_cloc_processed_sha.txt

      - name: Upload cloc Report Artifact
        if: steps.decide_run.outputs.run_cloc == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cloc-monthly-report-${{ env.REPORT_FILENAME }}
          path: ${{ env.REPORT_FILENAME }}
          retention-days: 90

      - name: Save last cloc-processed SHA to cache
        if: steps.decide_run.outputs.run_cloc == 'true' && steps.run_cloc_step.outcome == 'success'
        uses: actions/cache/save@v4
        with:
          path: .last_cloc_processed_sha.txt
          key: cloc-processed-sha-${{ github.ref_name }}
